#
# Travis CI
#
# @link https://docs.travis-ci.com/
# @link https://www.khs1994.com/categories/CI/Travis-CI/
#

language: php

cache:
  directories:
    - cache

sudo: required

services:
  # - docker
  # - rabbitmq
  # - memcached
  - redis-server
  - mysql
  # - mariadb
  # - postgresql
  # - mongodb

php:
  # - 5.6
  # - 7.0
  # - 7.1
  - 7.2

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

#
# 设置数据库
#
# @link https://docs.travis-ci.com/user/database-setup/
#
# addons:
#   mariadb: '10.0'
#   postgresql: '9.4'
before_script:
  - sleep 15
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS tests_tmp;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'CREATE DATABASE tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'CREATE DATABASE tests_tmp;' -U postgres; fi"
  - sh -c "if [ '$ENABLE_MONGODB' = 'enable' ]; then mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS pcit_test;'; fi"
  - if [ "$DB" = 'mysql' ]; then sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('mytest') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"; fi
  - if [ "$DB" = 'mysql' ]; then sudo mysql_upgrade -u root -pmytest; fi
  - if [ "$DB" = 'mysql' ]; then sudo service mysql restart; fi

jobs:
  include:
    - stage: test
      install:
        - curl -fsSL http://get.sensiolabs.org/sami.phar -o sami
        - chmod +x sami
        - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
      script:
        - composer install -q
        # - composer update -q
        - vendor/bin/phpunit --coverage-clover=coverage.xml
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - ./sami update .sami.php
      deploy:
        provider: pages
        skip-cleanup: true
        local-dir: build
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        on:
          branch: master
    # - stage: deploy
    #   script: " if ! [ -z \"${TRAVIS_TAG}\" ];then
    #   echo \"${TRAVIS_TAG}\" ;
    #   docker build -t khs1994/php-fpm:swarm-7.2.0-alpine3.7-${TRAVIS_TAG} --target=php . ;
    #   docker build -t khs1994/nginx:swarm-1.13.0-alpine-${TRAVIS_TAG} . ;
    #   docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} ;
    #   docker push khs1994/php-fpm:swarm-7.2.0-alpine3.7-${TRAVIS_TAG} ;
    #   docker push khs1994/nginx:swarm-1.13.0-alpine-${TRAVIS_TAG} ;
    #   else
    #   echo \"NOT TAG, Don't Build\";
    #   fi "

stages:
  - test
  # - name: deploy
  #   if: tag =~ ^[0-9.]+$

env:
  global:
    - MONGODB=disable
    # - DB=sqlite
    - DB=mysql
    # - DB=postgresql
    - CI_REDIS_HOST=localhost
    - CI_MYSQL_HOST=127.0.0.1
    - CI_MYSQL_USERNAME=root
    - CI_MYSQL_PASSWORD=mytest
    - CI_MYSQL_DBNAME=pcit_test

#
# rabbitmq vhost / username guest password guest
#

#
# mysql 127.0.0.1 username-> root/travis 空密码
#
# memcached/redis -> localhost
#
