version: "3.7"

services:

  pcit:
    build:
      context: .
      dockerfile: Dockerfile
      target: php
      args:
        - PHP_VERSION=${PHP_VERSION:-7.2.11}-fpm-alpine
        - NODE_VERSION=${NODE_VERSION:-alpine}
    image: khs1994/pcit:alpine
